// <auto-generated />
using System;
using GestaoTarefa.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestaoTarefa.Infra.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240923221358_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestaoTarefa.Domain.Entities.Setor", b =>
                {
                    b.Property<Guid>("SetorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SetorId");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("SETOR", (string)null);
                });

            modelBuilder.Entity("GestaoTarefa.Domain.Entities.Tarefa", b =>
                {
                    b.Property<Guid>("TarefaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Prioridade")
                        .HasColumnType("int");

                    b.Property<Guid>("SetorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TarefaId");

                    b.HasIndex("SetorId");

                    b.ToTable("TAREFA", (string)null);
                });

            modelBuilder.Entity("GestaoTarefa.Domain.Entities.Tarefa", b =>
                {
                    b.HasOne("GestaoTarefa.Domain.Entities.Setor", "Setor")
                        .WithMany("Tarefas")
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("GestaoTarefa.Domain.Entities.Setor", b =>
                {
                    b.Navigation("Tarefas");
                });
#pragma warning restore 612, 618
        }
    }
}
